// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResumeAI.Template.Data;

#nullable disable

namespace ResumeAI.Template.Migrations
{
    [DbContext(typeof(TemplateDbContext))]
    [Migration("20260427203650_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResumeAI.Template.Entities.ResumeTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("template_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TemplateId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CssStyles")
                        .HasColumnType("text")
                        .HasColumnName("css_styles");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("HtmlLayout")
                        .HasColumnType("text")
                        .HasColumnName("html_layout");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean")
                        .HasColumnName("is_premium");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("thumbnail_url");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer")
                        .HasColumnName("usage_count");

                    b.HasKey("TemplateId");

                    b.HasIndex("Category");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsPremium");

                    b.HasIndex("UsageCount");

                    b.ToTable("resume_templates");

                    b.HasData(
                        new
                        {
                            TemplateId = 1,
                            Category = "PROFESSIONAL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CssStyles = ".resume { font-family: 'Times New Roman', serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #222; }\n.resume-header { text-align: center; border-bottom: 2px solid #222; padding-bottom: 16px; margin-bottom: 24px; }\n.resume-header h1 { font-size: 28px; margin: 0; }\nsection { margin-bottom: 24px; }\nh2 { font-size: 16px; text-transform: uppercase; border-bottom: 1px solid #999; padding-bottom: 4px; }",
                            Description = "A clean, traditional layout ideal for corporate and finance roles. ATS-friendly structure.",
                            HtmlLayout = "<div class=\"resume\">\n  <header class=\"resume-header\">\n    <h1>{{FullName}}</h1>\n    <p>{{Email}} | {{Phone}} | {{Location}}</p>\n  </header>\n  <section class=\"summary\"><h2>Professional Summary</h2><p>{{Summary}}</p></section>\n  <section class=\"experience\"><h2>Work Experience</h2>{{Experience}}</section>\n  <section class=\"education\"><h2>Education</h2>{{Education}}</section>\n  <section class=\"skills\"><h2>Skills</h2>{{Skills}}</section>\n</div>",
                            IsActive = true,
                            IsPremium = false,
                            Name = "Classic Professional",
                            ThumbnailUrl = "/thumbnails/classic-professional.png",
                            UsageCount = 0
                        },
                        new
                        {
                            TemplateId = 2,
                            Category = "MODERN",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CssStyles = ".resume { font-family: 'Segoe UI', sans-serif; display: flex; max-width: 820px; margin: 0 auto; }\n.sidebar { width: 280px; background: #2d3748; color: #fff; padding: 32px 24px; }\n.sidebar h1 { font-size: 22px; margin-bottom: 8px; }\n.content { flex: 1; padding: 32px; }\nh2 { font-size: 15px; color: #2d3748; text-transform: uppercase; border-bottom: 2px solid #2d3748; }",
                            Description = "A clean two-column layout with a side accent bar. Great for tech and startup roles.",
                            HtmlLayout = "<div class=\"resume two-col\">\n  <aside class=\"sidebar\">\n    <h1>{{FullName}}</h1>\n    <p>{{Email}}</p><p>{{Phone}}</p>\n    <h3>Skills</h3>{{Skills}}\n  </aside>\n  <main class=\"content\">\n    <section><h2>Summary</h2><p>{{Summary}}</p></section>\n    <section><h2>Experience</h2>{{Experience}}</section>\n    <section><h2>Education</h2>{{Education}}</section>\n  </main>\n</div>",
                            IsActive = true,
                            IsPremium = false,
                            Name = "Modern Minimal",
                            ThumbnailUrl = "/thumbnails/modern-minimal.png",
                            UsageCount = 0
                        },
                        new
                        {
                            TemplateId = 3,
                            Category = "ATS_OPTIMISED",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CssStyles = ".resume.ats { font-family: Arial, sans-serif; max-width: 750px; margin: 0 auto; padding: 32px; color: #000; }\nh1 { font-size: 24px; margin-bottom: 4px; }\nh2 { font-size: 14px; text-transform: uppercase; margin-top: 20px; margin-bottom: 6px; }\np, li { font-size: 13px; line-height: 1.6; }",
                            Description = "Single-column plain text layout designed to score 90+ on ATS systems. No tables or graphics.",
                            HtmlLayout = "<div class=\"resume ats\">\n  <h1>{{FullName}}</h1>\n  <p>{{Email}} | {{Phone}}</p>\n  <h2>Summary</h2><p>{{Summary}}</p>\n  <h2>Experience</h2>{{Experience}}\n  <h2>Education</h2>{{Education}}\n  <h2>Skills</h2>{{Skills}}\n  <h2>Certifications</h2>{{Certifications}}\n</div>",
                            IsActive = true,
                            IsPremium = false,
                            Name = "ATS Optimised",
                            ThumbnailUrl = "/thumbnails/ats-optimised.png",
                            UsageCount = 0
                        },
                        new
                        {
                            TemplateId = 4,
                            Category = "CREATIVE",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CssStyles = ".resume.creative { font-family: 'Montserrat', sans-serif; max-width: 860px; margin: 0 auto; }\nheader { background: #e63946; color: #fff; padding: 40px; }\nheader h1 { font-size: 36px; margin: 0; }\n.tagline { font-size: 16px; opacity: 0.85; }\n.grid { display: grid; grid-template-columns: 1fr 2fr; gap: 0; }\n.left { background: #f8f9fa; padding: 32px; }\n.right { padding: 32px; }\nh2 { color: #e63946; font-size: 13px; text-transform: uppercase; letter-spacing: 1px; }",
                            Description = "Bold typography with colour accents. Perfect for designers, marketers, and creatives. Premium only.",
                            HtmlLayout = "<div class=\"resume creative\">\n  <header><h1>{{FullName}}</h1><span class=\"tagline\">{{TargetJobTitle}}</span></header>\n  <div class=\"grid\">\n    <div class=\"left\">\n      <section><h2>About</h2><p>{{Summary}}</p></section>\n      <section><h2>Skills</h2>{{Skills}}</section>\n      <section><h2>Languages</h2>{{Languages}}</section>\n    </div>\n    <div class=\"right\">\n      <section><h2>Experience</h2>{{Experience}}</section>\n      <section><h2>Projects</h2>{{Projects}}</section>\n    </div>\n  </div>\n</div>",
                            IsActive = true,
                            IsPremium = true,
                            Name = "Creative Portfolio",
                            ThumbnailUrl = "/thumbnails/creative-portfolio.png",
                            UsageCount = 0
                        },
                        new
                        {
                            TemplateId = 5,
                            Category = "MINIMALIST",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CssStyles = ".resume.executive { font-family: 'Garamond', Georgia, serif; max-width: 760px; margin: 60px auto; padding: 0 40px; color: #1a1a1a; }\nheader { border-bottom: 3px solid #1a1a1a; padding-bottom: 20px; margin-bottom: 32px; }\nh1 { font-size: 32px; font-weight: normal; letter-spacing: 2px; text-transform: uppercase; }\n.contact { font-size: 12px; color: #666; letter-spacing: 1px; }\nh2 { font-size: 11px; text-transform: uppercase; letter-spacing: 3px; color: #666; margin-top: 28px; }",
                            Description = "Ultra-clean layout with generous white space. Ideal for senior professionals and executives. Premium only.",
                            HtmlLayout = "<div class=\"resume executive\">\n  <header>\n    <h1>{{FullName}}</h1>\n    <p class=\"contact\">{{Email}} &bull; {{Phone}} &bull; {{Location}}</p>\n  </header>\n  <section><h2>Summary</h2><p>{{Summary}}</p></section>\n  <section><h2>Experience</h2>{{Experience}}</section>\n  <section><h2>Education</h2>{{Education}}</section>\n  <section><h2>Core Competencies</h2>{{Skills}}</section>\n</div>",
                            IsActive = true,
                            IsPremium = true,
                            Name = "Executive Minimalist",
                            ThumbnailUrl = "/thumbnails/executive-minimalist.png",
                            UsageCount = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
