using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using ResumeAI.Section.Enums;

namespace ResumeAI.Section.Entities;

[Table("resume_sections")]
public class ResumeSection
{
    [Key]
    [Column("section_id")]
    public int SectionId { get; set; }

    /// <summary>References resumes table (Resume Service — same DB).</summary>
    [Required]
    [Column("resume_id")]
    public int ResumeId { get; set; }

    /// <summary>Owner of the resume — from JWT for auth checks.</summary>
    [Required]
    [Column("user_id")]
    public int UserId { get; set; }

    /// <summary>Stored as string in DB via HasConversion.</summary>
    [Required]
    [Column("section_type")]
    public SectionType SectionType { get; set; } = SectionType.CUSTOM;

    [Required]
    [MaxLength(200)]
    [Column("title")]
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Rich text content stored as a JSON string.
    /// Example: {"text":"...", "bullets":["...","..."]}
    /// Section Service stores and retrieves as-is — no parsing.
    /// </summary>
    [Column("content", TypeName = "text")]
    public string? Content { get; set; }

    /// <summary>Used for drag-and-drop ordering. Lower value = higher position.</summary>
    [Column("display_order")]
    public int DisplayOrder { get; set; } = 0;

    /// <summary>Hides the section from the resume preview without deleting it.</summary>
    [Column("is_visible")]
    public bool IsVisible { get; set; } = true;

    /// <summary>
    /// True when this section's content was generated by the AI Service.
    /// Set to true by AI Service when calling UpdateSection.
    /// </summary>
    [Column("ai_generated")]
    public bool AiGenerated { get; set; } = false;

    [Column("created_at")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    [Column("updated_at")]
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
}
