using System.Text.Json;
using AutoMapper;
using ResumeAI.Export.DTOs.Request;
using ResumeAI.Export.DTOs.Response;
using ResumeAI.Export.Entities;
using ResumeAI.Export.Enums;
using ResumeAI.Export.Models;
using ResumeAI.Export.Repositories.Interfaces;
using ResumeAI.Export.Services.Interfaces;

namespace ResumeAI.Export.Services;

public class ExportService : IExportService
{
    private readonly IExportRepository     _exportRepo;
    private readonly IPdfRenderer          _pdfRenderer;
    private readonly IDocxRenderer         _docxRenderer;
    private readonly IMapper               _mapper;
    private readonly ILogger<ExportService> _logger;

    private const int FreePdfDailyLimit = 10;

    public ExportService(
        IExportRepository exportRepo,
        IPdfRenderer pdfRenderer,
        IDocxRenderer docxRenderer,
        IMapper mapper,
        ILogger<ExportService> logger)
    {
        _exportRepo   = exportRepo;
        _pdfRenderer  = pdfRenderer;
        _docxRenderer = docxRenderer;
        _mapper       = mapper;
        _logger       = logger;
    }

    // PDF Export
    public async Task<(byte[] FileBytes, ExportJob Job)> ExportToPdfAsync(
        int userId, string subscriptionPlan, ExportPdfRequest request, CancellationToken ct = default)
    {
        // Enforce FREE tier daily PDF limit
        if (!subscriptionPlan.Equals("PREMIUM", StringComparison.OrdinalIgnoreCase))
        {
            var todayCount = await _exportRepo.CountPdfByUserIdTodayAsync(userId, ct);
            if (todayCount >= FreePdfDailyLimit)
                throw new InvalidOperationException(
                    $"Free plan users can export a maximum of {FreePdfDailyLimit} PDFs per day. " +
                    "Upgrade to Premium for unlimited exports.");
        }

        var job = await CreateJobAsync(userId, request.ResumeId, ExportFormat.PDF, request.TemplateId, request.Customizations, ct);

        try
        {
            var fileBytes = _pdfRenderer.Render(request.ResumeData);
            await CompleteJobAsync(job, fileBytes.Length, ct);
            _logger.LogInformation("PDF exported for resume {ResumeId} by user {UserId}", request.ResumeId, userId);
            return (fileBytes, job);
        }
        catch (Exception ex)
        {
            await FailJobAsync(job, ex.Message, ct);
            throw;
        }
    }

    // DOCX Export
    public async Task<(byte[] FileBytes, ExportJob Job)> ExportToDocxAsync(
        int userId, ExportDocxRequest request, CancellationToken ct = default)
    {
        var job = await CreateJobAsync(userId, request.ResumeId, ExportFormat.DOCX, request.TemplateId, null, ct);

        try
        {
            var fileBytes = _docxRenderer.Render(request.ResumeData);
            await CompleteJobAsync(job, fileBytes.Length, ct);
            _logger.LogInformation("DOCX exported for resume {ResumeId} by user {UserId}", request.ResumeId, userId);
            return (fileBytes, job);
        }
        catch (Exception ex)
        {
            await FailJobAsync(job, ex.Message, ct);
            throw;
        }
    }

    // JSON Export
    public async Task<(byte[] FileBytes, ExportJob Job)> ExportToJsonAsync(
        int userId, ExportJsonRequest request, CancellationToken ct = default)
    {
        var job = await CreateJobAsync(userId, request.ResumeId, ExportFormat.JSON, null, null, ct);

        try
        {
            var json      = JsonSerializer.Serialize(request.ResumeData, new JsonSerializerOptions { WriteIndented = true });
            var fileBytes = System.Text.Encoding.UTF8.GetBytes(json);
            await CompleteJobAsync(job, fileBytes.Length, ct);
            _logger.LogInformation("JSON exported for resume {ResumeId} by user {UserId}", request.ResumeId, userId);
            return (fileBytes, job);
        }
        catch (Exception ex)
        {
            await FailJobAsync(job, ex.Message, ct);
            throw;
        }
    }

    // Job Status
    public async Task<ExportJobResponse?> GetJobStatusAsync(string jobId, CancellationToken ct = default)
    {
        var job = await _exportRepo.FindByJobIdAsync(jobId, ct);
        return job is null ? null : _mapper.Map<ExportJobResponse>(job);
    }

    // Get all exports for a user
    public async Task<IList<ExportJobResponse>> GetExportsByUserAsync(int userId, CancellationToken ct = default)
    {
        var jobs = await _exportRepo.FindByUserIdAsync(userId, ct);
        return _mapper.Map<IList<ExportJobResponse>>(jobs);
    }

    // Download file — since files are not stored on disk, this returns job metadata
    // The actual file must be regenerated by the client calling the export endpoint again
    // For a production system with cloud storage this would fetch from Azure/S3
    public async Task<(byte[] FileBytes, string FileName, string ContentType)?> DownloadFileAsync(
        string jobId, int userId, CancellationToken ct = default)
    {
        var job = await _exportRepo.FindByJobIdAsync(jobId, ct);
        if (job is null || job.UserId != userId)
            throw new KeyNotFoundException($"Export job {jobId} not found.");

        if (job.Status != ExportStatus.COMPLETED)
            throw new InvalidOperationException($"Export job is {job.Status}. Only COMPLETED exports can be downloaded.");

        // Since we stream files directly and don't persist them, return metadata indicating re-export is needed
        throw new InvalidOperationException(
            "Direct download is only available when cloud storage is configured. " +
            "Please re-export your resume to download the latest version.");
    }

    // Delete export job record
    public async Task DeleteExportAsync(string jobId, int userId, CancellationToken ct = default)
    {
        var job = await _exportRepo.FindByJobIdAsync(jobId, ct)
            ?? throw new KeyNotFoundException($"Export job {jobId} not found.");

        if (job.UserId != userId)
            throw new UnauthorizedAccessException("You do not have permission to delete this export.");

        await _exportRepo.DeleteByJobIdAsync(jobId, ct);
        _logger.LogInformation("Export job {JobId} deleted by user {UserId}", jobId, userId);
    }

    // Cleanup expired export records — called daily by IHostedService
    public async Task CleanupExpiredExportsAsync(CancellationToken ct = default)
    {
        await _exportRepo.DeleteExpiredAsync(ct);
        _logger.LogInformation("Expired export records cleaned up at {Time}", DateTime.UtcNow);
    }

    // Export stats for the user
    public async Task<ExportStatsResponse> GetExportStatsAsync(int userId, string subscriptionPlan, CancellationToken ct = default)
    {
        var allJobs   = await _exportRepo.FindByUserIdAsync(userId, ct);
        var todayPdf  = await _exportRepo.CountPdfByUserIdTodayAsync(userId, ct);
        var isPremium = subscriptionPlan.Equals("PREMIUM", StringComparison.OrdinalIgnoreCase);

        return new ExportStatsResponse
        {
            TotalExports   = allJobs.Count,
            PdfExports     = allJobs.Count(j => j.Format == ExportFormat.PDF),
            DocxExports    = allJobs.Count(j => j.Format == ExportFormat.DOCX),
            JsonExports    = allJobs.Count(j => j.Format == ExportFormat.JSON),
            ExportsToday   = todayPdf,
            RemainingToday = isPremium ? -1 : Math.Max(0, FreePdfDailyLimit - todayPdf)
        };
    }

    // Helpers
    private async Task<ExportJob> CreateJobAsync(
        int userId, int resumeId, ExportFormat format,
        int? templateId, string? customizations, CancellationToken ct)
    {
        var job = new ExportJob
        {
            JobId          = Guid.NewGuid().ToString(),
            UserId         = userId,
            ResumeId       = resumeId,
            Format         = format,
            Status         = ExportStatus.PROCESSING,
            TemplateId     = templateId,
            Customizations = customizations
        };
        return await _exportRepo.CreateAsync(job, ct);
    }

    private async Task CompleteJobAsync(ExportJob job, int fileSizeBytes, CancellationToken ct)
    {
        job.Status      = ExportStatus.COMPLETED;
        job.CompletedAt = DateTime.UtcNow;
        job.FileSizeKb  = fileSizeBytes / 1024;
        job.FileUrl     = $"/api/exports/download/{job.JobId}";
        await _exportRepo.UpdateAsync(job, ct);
    }

    private async Task FailJobAsync(ExportJob job, string error, CancellationToken ct)
    {
        job.Status       = ExportStatus.FAILED;
        job.CompletedAt  = DateTime.UtcNow;
        job.ErrorMessage = error;
        await _exportRepo.UpdateAsync(job, ct);
    }
}
