using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using ResumeAI.Export.Models;

namespace ResumeAI.Export.Services;

public interface IPdfRenderer
{
    byte[] Render(ResumeData resume);
}

public class QuestPdfRenderer : IPdfRenderer
{
    public byte[] Render(ResumeData resume)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(t => t.FontSize(10).FontFamily("Arial"));

                page.Content().Column(col =>
                {
                    // Header
                    col.Item().BorderBottom(2).BorderColor(Colors.Grey.Darken2)
                        .PaddingBottom(8).Column(header =>
                    {
                        header.Item().Text(resume.FullName)
                            .FontSize(22).Bold().FontColor(Colors.Black);

                        if (!string.IsNullOrWhiteSpace(resume.TargetJobTitle))
                            header.Item().Text(resume.TargetJobTitle)
                                .FontSize(12).FontColor(Colors.Grey.Darken1);

                        var contactParts = new List<string>();
                        if (!string.IsNullOrWhiteSpace(resume.Email))    contactParts.Add(resume.Email);
                        if (!string.IsNullOrWhiteSpace(resume.Phone))    contactParts.Add(resume.Phone);
                        if (!string.IsNullOrWhiteSpace(resume.Location)) contactParts.Add(resume.Location);

                        if (contactParts.Count > 0)
                            header.Item().Text(string.Join("  |  ", contactParts))
                                .FontSize(9).FontColor(Colors.Grey.Darken1);
                    });

                    col.Item().Height(12);

                    // Summary section
                    if (!string.IsNullOrWhiteSpace(resume.Summary))
                    {
                        col.Item().Column(s =>
                        {
                            s.Item().Text("PROFESSIONAL SUMMARY")
                                .FontSize(10).Bold().FontColor(Colors.Grey.Darken2);
                            s.Item().Height(4);
                            s.Item().Text(resume.Summary).FontSize(10).LineHeight(1.4f);
                            s.Item().Height(10);
                        });
                    }

                    // Resume sections ordered by DisplayOrder
                    var visibleSections = resume.Sections
                        .Where(s => s.IsVisible)
                        .OrderBy(s => s.DisplayOrder)
                        .ToList();

                    foreach (var section in visibleSections)
                    {
                        if (string.IsNullOrWhiteSpace(section.Content)) continue;

                        col.Item().Column(s =>
                        {
                            s.Item().Text(section.Title.ToUpper())
                                .FontSize(10).Bold().FontColor(Colors.Grey.Darken2);
                            s.Item().Height(2);
                            s.Item().BorderTop(1).BorderColor(Colors.Grey.Lighten1).Height(1);
                            s.Item().Height(4);
                            s.Item().Text(section.Content).FontSize(10).LineHeight(1.4f);
                            s.Item().Height(10);
                        });
                    }
                });

                page.Footer().AlignCenter()
                    .Text(t =>
                    {
                        t.Span("Generated by ResumeAI  •  ").FontSize(8).FontColor(Colors.Grey.Medium);
                        t.CurrentPageNumber().FontSize(8).FontColor(Colors.Grey.Medium);
                        t.Span(" / ").FontSize(8).FontColor(Colors.Grey.Medium);
                        t.TotalPages().FontSize(8).FontColor(Colors.Grey.Medium);
                    });
            });
        });

        return document.GeneratePdf();
    }
}
